name: table_order
description: "Table Order App (customer + admin in one)"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # 기본 UI
  cupertino_icons: ^1.0.8
  cached_network_image: any # ✅ 고객 모드 이미지 캐싱/플레이스홀더
  intl: ^0.20.2
  lucide_icons_flutter: ^3.1.5

  # 상태관리
  provider: ^6.1.5+1

  # 로컬 저장
  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4 # ✅ 관리자 업로드 / 고객 다운로드

  # 로컬 이미지 선택
  image_picker: ^1.2.1 # ✅ 사장님이 태블릿 갤러리에서 선택

  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
