name: table_order
description: "Table Order App (customer + admin in one)"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # 기본 UI
  cupertino_icons: ^1.0.8
  flutter_svg: any
  cached_network_image: any # ✅ 고객 모드 이미지 캐싱/플레이스홀더
  intl: any
  lucide_icons_flutter: ^3.1.5

  # 상태관리
  provider: any

  # 로컬 저장
  shared_preferences: any

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any # ✅ 관리자 업로드 / 고객 다운로드

  # 로컬 이미지 선택 + 경로 접근
  image_picker: any # ✅ 사장님이 태블릿 갤러리에서 선택
  path_provider: any # ✅ 업로드 전 임시 저장 등

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
